version: "2"
services:
  app:
    build: .
    image: tomazjr/node-webhook:latest
    environment:
      - WH_MONGO_URL=mongodb://mongodb:27017
    ports:
      - "3010:3010"
    links:
      - mongodb
    depends_on:
      - mongodb
    command: npm start
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
